### ISSUE TITLE
IPFS: Can't pin files on previously working system

### ISSUE THREAD

**Issue by Suika** [hydrusnetwork/hydrus#894]
## Environment

Hydrus version: 441
Platform: docker
OS specifics: docker

## What happens
After upgrade to 441 from 338, ipfs stopped pinning files.

## Steps to reproduce

1. Upgrade 338 > 441
2. Try to pin files to ipfs
3. Error

## Desired outcome

Working ipfs

## Error message / Log file / Screenshots
```python
DBException
AttributeError: 'ServiceIPFS' object has no attribute 'GetAccount'
Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/gui/ClientGUI.py", line 213, in THREADUploadPending
    result = HG.client_controller.Read( 'pending', service_key, content_types_to_request )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 625, in Read
    return self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 199, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 1101, in Read
    return job.GetResult()
  File "/opt/hydrus/hydrus/core/HydrusData.py", line 1826, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: AttributeError: 'ServiceIPFS' object has no attribute 'GetAccount'
Database Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 727, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 15050, in _Read
    elif action == 'pending': result = self._GetPending( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 11437, in _GetPending
    account = service.GetAccount()
AttributeError: 'ServiceIPFS' object has no attribute 'GetAccount'


Database Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 727, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 15050, in _Read
    elif action == 'pending': result = self._GetPending( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 11437, in _GetPending
    account = service.GetAccount()
AttributeError: 'ServiceIPFS' object has no attribute 'GetAccount'

```

**Comment by hydrusnetwork** [comment]
Thank you for this report, I am sorry for the trouble! I fixed one thing here for 441, looks like there is something else.
