### ISSUE TITLE
All network jobs failing after upgrade to v656

### ISSUE THREAD

**Issue by mag2340** [hydrusnetwork/hydrus#1953]
### Hydrus version

v656

### Qt major version

Qt 5

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

OS: Linux Mint 21.2 x86_64
Kernel: 5.15.0-164-generic

### Bug description and reproduction

Upgraded from v654 to v656 a couple days ago. After upgrading, all network jobs (direct URL downloads and subscriptions) fail with the same traceback message, no matter which website is used. Tested on my Windows install (also running source) and had no issues there.

### Log output

```text
v656, linux, source
AttributeError
'ExtractResult' object has no attribute 'top_domain_under_public_suffix'
================ Exception ================
AttributeError: 'ExtractResult' object has no attribute 'top_domain_under_public_suffix'
================ Traceback ================
Traceback (most recent call last):
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 1724, in Sync
    self._SyncQueries( job_status )
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 332, in _SyncQueries
    self._SyncQuery( job_status, gug, query_header, query_log_container, status_prefix )
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 417, in _SyncQuery
    ( login_ok, login_reason ) = query_header.GalleryLoginOK( CG.client_controller.network_engine, self._name )
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptionQuery.py", line 442, in GalleryLoginOK
    nj = self._example_gallery_seed.GetExampleNetworkJob( self._GenerateNetworkJobFactory( subscription_name ) )
  File "<hydrus_path>/hydrus/client/importing/ClientImportGallerySeeds.py", line 348, in GetExampleNetworkJob
    network_job = network_job_factory( 'GET', url_to_fetch )
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptionQuery.py", line 136, in network_job_factory
    network_job = ClientNetworkingJobs.NetworkJobSubscription( subscription_key, *args, **kwargs )
  File "<hydrus_path>/hydrus/client/networking/ClientNetworkingJobs.py", line 1996, in __init__
    super().__init__( method, url, body = body, referral_url = referral_url, temp_path = temp_path )
  File "<hydrus_path>/hydrus/client/networking/ClientNetworkingJobs.py", line 170, in __init__
    self._second_level_domain = ClientNetworkingFunctions.ConvertURLIntoSecondLevelDomain( self._url )
  File "<hydrus_path>/hydrus/client/networking/ClientNetworkingFunctions.py", line 364, in ConvertURLIntoSecondLevelDomain
    return ConvertDomainIntoSecondLevelDomain( domain )
  File "<hydrus_path>/hydrus/client/networking/ClientNetworkingFunctions.py", line 138, in ConvertDomainIntoSecondLevelDomain
    return ClientNetworkingDomainTLDExtract.ConvertDomainIntoSecondLevelDomain( domain )
  File "<hydrus_path>/hydrus/client/networking/ClientNetworkingDomainTLDExtract.py", line 26, in ConvertDomainIntoSecondLevelDomain
    return tldextract.extract( domain ).top_domain_under_public_suffix
AttributeError: 'ExtractResult' object has no attribute 'top_domain_under_public_suffix'
================== Stack ==================
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<hydrus_path>/hydrus/core/processes/HydrusThreading.py", line 416, in run
    callable( *args, **kwargs )
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 1855, in Work
    self._DoWork()
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 1841, in _DoWork
    self._subscription.Sync()
  File "<hydrus_path>/hydrus/client/importing/ClientImportSubscriptions.py", line 1754, in Sync
    HydrusData.ShowException( e )
  File "<hydrus_path>/hydrus/client/ClientData.py", line 174, in ShowExceptionClient
    ShowExceptionTupleClient( etype, value, tb, do_wait = do_wait )
  File "<hydrus_path>/hydrus/client/ClientData.py", line 213, in ShowExceptionTupleClient
    message = HydrusData.PrintExceptionTuple( etype, value, tb, do_wait = False )
  File "<hydrus_path>/hydrus/core/HydrusData.py", line 335, in PrintExceptionTuple
    stack_list = traceback.format_stack()
=================== End ===================
```

**Comment by roachcord3** [comment]
Under the release notes you can see there is stuff about the `tldextract` module being an optional dependency related to some new functionality. Though, it looks like the dev didn't put it in any of the requirements files, even for advanced/test users, so chances are one of the following is the case:

1. Your Windows install has `tldextract` available in the python environment running hydrus there, but your Linux install doesn't.
    1. Maybe you installed the module manually on Windows but not Linux, and forgot about it?
    2. Maybe you don't use a virtualenv on Windows and you're running on system python and system modules, and you just happen to have `tldextract` installed system-wide there? Or vice-versa with Linux? If it's this one, you should switch to using virtualenvs always, since chaos happens when you install python packages system-wide.
2. Your Windows client is not doing anything that would invoke this new optional logic.

Regardless, based on the code, it looks like there's also a problem with the version of `tldextract` installed. Hydev is gonna have to assert that it has certain properties or its module is of at least a certain version in the code alongside trying to import it, or else properly make it a dependency of his project, cuz you're passing the [import check](https://github.com/hydrusnetwork/hydrus/blob/e464eaa449e79e26316c692045c9d5264a7f9ecd/hydrus/client/networking/ClientNetworkingDomainTLDExtract.py#L7-L15) but your version of the library doesn't have this attribute that the code expects. Looks like this property was added in [the 5.3.0 release](https://github.com/john-kurkowski/tldextract/releases/tag/5.3.0), so you will need to make sure that version is what you have installed. That, or I guess make sure it's not installed in the virtualenv you have hydrus using.

**Comment by hydrusnetwork** [comment]
Hey, thank you for this report. I am very sorry! I snuck this thing in assuming essentially no-one would have this library in their source environment yet, and then not only did you, you had a version that raised an error.

I've fixed this for tomorrow's v657. You'll get the error in your log, silently, one time per boot. It'll fall back to the old domain calculation here and you shouldn't have any more problems.

Can you walk me through how you run hydrus on Linux? Is it with a venv set up with one of my setup_venv scripts, or are you on something like AUR/Arch? If you know, is it possible your python is not in a venv but is instead sharing an environment with other programs?

In any case, please update to v657 when convenient after tomorrow and let me know if you have any more problems. Since I plan to integrate this library for real in the next month or so, you may be looking at wanting to update your Linux venv/env/whatever you have here. It depends on what your current situation is.

If you are able to inspect and update your environment manually, going up to `tldextract==5.3.1` should sort you out immediately here.

**Comment by mag2340** [comment]
> Can you walk me through how you run hydrus on Linux? Is it with a venv set up with one of my setup_venv scripts, or are you on something like AUR/Arch?

Yes I'm using your `setup_venv.sh` script, no I'm not on Arch or using AUR. In short, I download the source code to a specific folder in `/home` then run `setup_venv.sh`. DB, files and thumbnails are hosted on a separate local host than the client workstation, over SMB. I have an alias in `.zshrc` that runs Hydrus via the following command: `python3 <hydrus path>/hydrus_client.py -d=<remote db path> &`

When I need to update, I normally use your `git_pull.sh` script.

>If you know, is it possible your python is not in a venv but is instead sharing an environment with other programs?
>If you are able to inspect and update your environment manually, going up to `tldextract==5.3.1` should sort you out immediately here.

Funny thing, I wrote out this big long paragraph of troubleshooting, but your questions made me realize that even though I'm running the `setup_venv.sh` script, Hydrus isn't using the venv pip packages, it's using the OS' pip packages. I didn't even have tldextract installed in my venv. I then upgraded it in venv, no change, then upgraded it in OS, and it works now (upgraded from 3.1.2). 

I assumed that Hydrus was automatically running the venv because I ran the setup_venv.sh script. Forgive me, I'm an amateur with Python and venvs, how am I supposed to run Hydrus to make sure it uses that venv's packages?

**Comment by hydrusnetwork** [comment]
Thank you, that's interesting. _Normally_, I would recommend that people launch a source install using the `hydrus_client.sh` script. There's a .bat for Windows. If you run hydrus with `python hydrus_client.py`, you'll use your system path, but if you look inside the `hydrus_client.sh`, you'll see a magic line where it calls some variant of:

`venv/something/activate`

Which does some environment magic to say 'hey, when I say python from now on, use the private python we set up in the venv'. That's how all venv stuff works, generally speaking.

Your original problem here is totally understandable, and I'm sorry again for not making it more clear what you want to do. Running `./hydrus_client.sh` or putting that in a shortcut or whatever works for you is the normal way to do it all.

Keeping the help updated and clear for all users is a constant battle. It sounds like you hit the normal 'running from source' help, since you did the `setup_venv.sh` stuff. Do you think it would help if I made the 'now run hydrus_client.sh, not the py' a bit more clear and in bold? Or maybe somewhere else?

Now I think of it, the setup_venv scripts themselves could have a 'Now run hydrus_client.sh to boot the program' or something at the end, too.

**Comment by mag2340** [comment]
From my perspective, yeah, just a brief clarification on how venv will only be used if you use `hydrus_client.sh` would be helpful, both after running `setup_venv.sh` and in the documentation. On the one hand, it's safe to assume that someone running from source would know enough to be able to do it properly. On the other hand, your documentation is so insanely helpful that amateur users can find themselves in the same position I was in and not know enough to dig their way out of it.

Anyway, thanks for being so helpful. I'll check out the update tomorrow but my issue is probably fixed now.

**Comment by hydrusnetwork** [comment]
Great. I will give that bit of the help a pass next week and have it improved for v658. Let me know if you run into any more trouble!
