### ISSUE TITLE
After update to v144 , export folders not working

### ISSUE THREAD

**Issue by disposablecat** [hydrusnetwork/hydrus#19]
I've been getting this error whenever I try to manage export folders, periodically (about every few minutes) while running, and when the client launches:

```
Daemon CheckExportFolders encountered an exception:
AttributeError

'Predicate' object has no attribute '_inclusive'

Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusThreading", line 110, in run
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 6332, in DAEMONCheckExportFolders
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientConstants", line 1559, in __init__
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusConstants", line 2191, in GetInclusive
AttributeError: 'Predicate' object has no attribute '_inclusive'

AttributeError

'Predicate' object has no attribute '_inclusive'

  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUI", line 1843, in EventMenu
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUI", line 1176, in _ManageExportFolders
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIDialogsManage", line 1494, in __init__
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIDialogsManage", line 1459, in PopulateControls
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIDialogsManage", line 1534, in _GetPrettyVariables
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientGUIDialogsManage", line 1534, in <genexpr>
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusConstants", line 2350, in GetUnicode
```

**Comment by disposablecat** [comment]
I tried to find a way to delete my export folder from the DB so I could see if that cleared the error (and then just recreate it), but I can't find where that particular configuration is stored.

**Comment by disposablecat** [comment]
Additionally persists across uninstall/reinstall, keeping same /db folder.

**Comment by hydrusnetwork** [comment]
Damn, I forgot about this when I changed how predicates work. I am sorry for this mistake.

I have added a patch for next week that should convert the old objects that are stored in your db to the new versions as they are queried. Please let me know if you get any more problems.

If you want to clear out the old export folder entries right now so you can recreate them manually, then open up client.db in sqlite studio and delete everything from yaml_dumps that has dump_type 6.

DELETE FROM yaml_dumps WHERE dump_type=6;

Or deleting each row manually will do the trick.

**Comment by disposablecat** [comment]
I went in and yanked it out manually - thanks for the DB location. I only had one, so it's easy.

Appreciate the quick fix!
